import { Product } from "@/types";

export const INITIAL_PRODUCTS: Product[] = [
  // 4 Roupas Elegantes (entre 18.000 Kz e 68.000 Kz)
  {
    id: "moir-prod-01",
    name: "Vestido Longo Seda Ébano",
    category: "Roupas",
    subcategory: "Vestidos de Gala",
    price: 54000,
    salePrice: 48000,
    stock: 8,
    description: "Confeccionado em pura seda acetinada de toque ultra suave, com caimento fluido impecável e decote sutil nas costas. Ideal para jantares de gala e celebrações exclusivas em Luanda.",
    imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80",
    variants: ["PP", "P", "M", "G", "GG"],
    featured: true,
  },
  {
    id: "moir-prod-02",
    name: "Camisa Linho Puro Riviera",
    category: "Roupas",
    subcategory: "Camisaria Premium",
    price: 28500,
    stock: 14,
    description: "Camisa clássica em linho europeu 100% natural com textura leve e respirável. Corte contemporâneo e botões de madrepérola natural para compor elegância descontraída.",
    imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80",
    variants: ["P", "M", "G", "GG"],
    featured: true,
  },
  {
    id: "moir-prod-03",
    name: "Blazer Alfaiataria Noite Luandense",
    category: "Roupas",
    subcategory: "Alfaiataria",
    price: 68000,
    salePrice: 59000,
    stock: 4, // estoque baixo para demonstrar o alerta no painel
    description: "Blazer de corte estruturado com lapela em cetim e forro acetinado personalizado. Uma peça de alta costura projetada para presença imponente em eventos formais.",
    imageUrl: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80",
    variants: ["PP", "P", "M", "G"],
    featured: true,
  },
  {
    id: "moir-prod-04",
    name: "Calça Pantalona Areia Dourada",
    category: "Roupas",
    subcategory: "Calças & Alfaiataria",
    price: 32000,
    stock: 11,
    description: "Pantalona de cintura alta com pregas frontais bem definidas e bolsos embutidos. Confeccionada em viscose encorpada com caimento sofisticado e movimento gracioso.",
    imageUrl: "https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?auto=format&fit=crop&w=800&q=80",
    variants: ["PP", "P", "M", "G", "GG"],
    featured: false,
  },

  // 4 Perfumes Importados de Luxo (entre 35.000 Kz e 145.000 Kz)
  {
    id: "moir-prod-05",
    name: "Moir Privé Oud & Ambre Extrait",
    category: "Perfumes",
    subcategory: "Nicho Oriental",
    price: 125000,
    salePrice: 115000,
    stock: 6,
    description: "Uma sinfonia rica de madeira de Oud nobre, âmbar resinoso e toques de açafrão persa. Concentração Extrait de Parfum com fixação de mais de 18 horas na pele.",
    imageUrl: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80",
    variants: ["30ml", "50ml", "100ml"],
    featured: true,
  },
  {
    id: "moir-prod-06",
    name: "Nuit de Luanda Eau de Parfum",
    category: "Perfumes",
    subcategory: "Amadeirado Floral",
    price: 85000,
    salePrice: 75000,
    stock: 9,
    description: "Inspirado nas brisas noturnas da Baía de Luanda. Combina notas frescas de bergamota italiana, flor de laranjeira radiante e fundo quente de sândalo e fava tonka.",
    imageUrl: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=800&q=80",
    variants: ["50ml", "100ml"],
    featured: true,
  },
  {
    id: "moir-prod-07",
    name: "Fleur Blanche de Cuanza Extrait",
    category: "Perfumes",
    subcategory: "Floral Gourmand",
    price: 145000,
    stock: 3, // estoque baixo para demonstrar indicador no painel
    description: "Obra-prima olfativa com acordes de jasmim sambac, baunilha de Bourbon e almíscar branco puro. Frasco facetado com tampa metálica dourada escovada.",
    imageUrl: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&w=800&q=80",
    variants: ["30ml", "50ml", "100ml"],
    featured: true,
  },
  {
    id: "moir-prod-08",
    name: "Vetiver Imperial Sauvage",
    category: "Perfumes",
    subcategory: "Cítrico Aromático",
    price: 49000,
    salePrice: 42000,
    stock: 12,
    description: "Elegância pura e revigorante. Notas efervescentes de toranja rosa, vetiver do Haiti terroso e pimenta rosa moída na hora. O clássico indispensável para o dia a dia executivo.",
    imageUrl: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80",
    variants: ["50ml", "100ml"],
    featured: false,
  },
];
